version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - ./.:/code:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
